export const UnitsLocators = {
  currencyDropdownButton: '.MuiAutocomplete-popupIndicator',
  pricePerSquareMeterBox: 'input[name="precioListaMetroCuadrado"]',
  expectedProfitBox: 'input[name="gananciaEsperada"]',
  floorsBox: 'input[name="pisos"]',
  basementsBox: 'input[name="subsuelos"]',
  typologiesDropdown: '[data-cy="new-renderer-field-tipologias"]',
  unitsPerFloorBox: 'input[name="unidadesPorPiso"]',
  parkingSpacesBox: 'input[name="cantidadCocheras"]',
  unitSubstatesDropdown: 'input[data-cy="new-renderer-field-subEstadosUnidades"]',
  plansDropdown: 'input[data-cy="new-renderer-field-planos"]',
  rendersDropdown: 'input[data-cy="new-renderer-field-renders"]',
  presentationsDropdown: 'input[data-cy="new-renderer-field-presentaciones"]',
  videosDropdown: 'input[data-cy="new-renderer-field-videos"]',
  modelContractDropdown: 'input[data-cy="new-renderer-field-boletoModelo"]',
  streetViewBox: 'input[name="streetView"]',
  googleMapsBox: 'input[name="googleMaps"]',
  pointsOfInterestDropdown: 'input[data-cy="new-renderer-field-lugaresDeInteres"]',
  priceListVersionBox: 'input[name="versionListaPrecios"]',
  saveButton: 'button:has-text("Guardar")',
  currencyDropdown: 'input[data-cy="new-renderer-field-moneda"]',
};