export const ProjectLocators = {
  projectTitle: 'text=PROYECTO',
  addProjectButton: 'button:has-text("Agregar proyecto")',
  addLogo: 'text=Subir logo del proyecto',
  logoUploadInput: 'input[id="file-logo del proyecto"]',
  nameProject: 'input[name="nombreProyecto"]',
  currencyDropdown: '[data-cy="new-renderer-field-moneda"]',
  defineAutomatically: 'input[type="checkbox"]',
  countryDropdown: '[data-cy="new-renderer-field-pais"]',
  stateDropdown: '[data-cy="new-renderer-field-estado"]',
  cityDropdown: '[data-cy="new-renderer-field-ciudad"]',
  streetBox: '[data-cy="new-renderer-field-calle"]',
  numberBox: '[data-cy="new-renderer-field-numeroPuerta"]',
  startDateBox: '[data-cy="new-renderer-field-fechaInicio"]',
  endDateBox: '[data-cy="new-renderer-field-fechaFin"]',
  constructionTypeDropdown: '[data-cy="new-renderer-field-tipoConstruccion"]',
  adjustmentModeDropdown: '[data-cy="new-renderer-field-modalidadAjuste"]',
  companyNameInput: 'input[placeholder="Escribí para buscar o crear"]',
  companyNameLabel: 'text=Nombre *',
  descriptionLabel: 'text=Descripción',
  registrationDateLabel: 'text=Fecha de registro *',
  documentTypeLabel: 'text=Tipo de documento *',
  cuitNumberLabel: 'label:has-text("Número de documento")',
  registerButton: 'button:has-text("Registrar")',
  exchangeRateInput: 'input[name="tipoDeCambio"]',
  backButton: 'button:has-text("Volver")',
  commercialOption: 'use[href*="#comercial"], use[xlink\\:href*="#comercial"]',
  unitsMenuOption: 'li[role="menuitem"] span:text-is("Unidades")',
  commercialExpandButton:'[xlink\\:href*="doubleArrowRight"]',

};